defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *defaults
  database: crypto_development
  username: pva

test:
  <<: *defaults
  database: crypto_test
  username: pva

production:
  adapter: postgresql
  encoding: unicode
  database: crypto_production
  pool: 5
  username: 
  password:
