# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5542c6de3b3c70f40f449db23bddc7178ef5260d5e921c8da51e0b4f91c809c32a76a7fbe6d2c301ee82e2cd28bba676770531f22222f3095fa76049cce8d9b0

test:
  secret_key_base: 08c457fd4b9ea9f0cad00135fde99a1bd3e06cf13122c195d69d85675283c90aeef281d63ee4812313d7a0edaca3530a01c4aac8191ac6f573041e4de39f2fa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
